version: "3.9"

services:
  daily-rise-api:
    container_name: daily-rise-api
    hostname: daily-rise-api
    image: daily-rise-api
    build:
      context: ../..
    depends_on:
      - daily-rise-database
      - daily-rise-database-migration
    environment:
      - DATABASE_URL

  daily-rise-database:
    container_name: daily-rise-database
    hostname: daily-rise-database
    image: postgres:15.2-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=daily_rise
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  daily-rise-database-migration:
    container_name: daily-rise-database-migration
    image: daily-rise-api
    build:
      context: ../..
    depends_on:
      - daily-rise-database
    environment:
      - DATABASE_URL
    command: [ "sh", "./scripts/database.sh", "deploy" ]