services:
    life-captain-api:
        image: life-captain-api
        build:
            context: ../..
        depends_on:
            - life-captain-database
            - life-captain-database-migration
        environment:
            - DATABASE_URL

    life-captain-database:
        image: postgres:15.2-alpine
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=life_captain
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 1s
            timeout: 5s
            retries: 42

    life-captain-database-migration:
        image: life-captain-api
        build:
            context: ../..
        depends_on:
            life-captain-database:
                condition: service_healthy
        environment:
            - DATABASE_URL
        command: [ "make", "db-deploy" ]
