name: Quality Pipeline

on:
    push:
        branches:
            - main
            - develop

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: make test

    lint-type:
        name: Lint for Type
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: make lint-type

    lint-code:
        name: Lint for Code
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: make lint-code

    lint-style:
        name: Lint for Style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: make lint-style
