name: Quality Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Run application tests
        run: make test

  lint-type:
      name: Type Check
      runs-on: ubuntu-latest
      steps:
          - name: Set up repository
            uses: actions/checkout@v4

          - name: Run type linter
            run: make lint-type

  lint-style:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Run style linter
        run: make lint-style
